version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm test

  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build:
          requires:
            - test
